### ISSUE TITLE
Implement `BitlapDriver`

### ISSUE THREAD

**Issue by jxnu-liguobin** [bitlap/bitlap#1]
Refer to the Java library [sqlite-jdbc](https://github.com/xerial/sqlite-jdbc/blob/master/src/main/java/org/sqlite/JDBC.java) to implement `BitlapDriver`.

**Comment by jxnu-liguobin** [comment]
Reference document: Javadoc https://docs.oracle.com/javase/8/docs/api/java/sql/Driver.html.

1.Add `BitlapJDBCLoader` to load local driver file
2.Add `BitlapConnection` for kotlin to wrap connection 
3.Implement `BitlapDriver`

Consider:
1.JDBC multi-version.

**Comment by IceMimosa** [comment]
@jxnu-liguobin niubility 😏

**Comment by jxnu-liguobin** [comment]
Four request-response api to use jdbc driver run a demo. Refer to hive jdbc.
- [ ] open session: BOpenSessionReq      BOpenSessionResp
- [ ] close session: BCloseSessionReq     BCloseSessionResp
- [ ] execute statement: BExecuteStatementReq BExecuteStatementResp
- [ ] fetch results: BFetchResultsReq    BFetchResultsResp

NOTE:
- session manage
- async execute, and how to get data
- discover server host. like zk in hive (at present, take no account of)
- two way: 1. socket (at present, take no account of) 2.rpc
-  sql engine (this issue doesn't care)
